version: '3'
services:
  list:
    build:
      context: .
      args:
        SRV_NAME: list
    image: gosamples/workshop-list
    container_name: workshop-list
    entrypoint: /go/bin/list
    depends_on:
      - db
    links:
      - db
    ports:
      - "50001:8080"

  users:
    build:
      context: .
      args:
        SRV_NAME: users
    image: gosamples/workshop-users
    container_name: workshop-users
    entrypoint: /go/bin/users
    depends_on:
      - list
      - db
    links:
      - list
      - db
    ports:
      - "50000:8080"

  notifier:
    build:
      context: .
      args:
        SRV_NAME: notifier
    image: gosamples/workshop-notifier
    container_name: workshop-notifier
    entrypoint: /go/bin/notifier
    ports:
      - "50002:8080"

  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    image: gosamples/workshop-web
    container_name: workshop-web
    depends_on:
      - list
      - users
    links:
      - list
      - users
    ports:
      - "3030:8080"

  db:
    image: nethost/mongo:3.4.4
    container_name: workshop-db
    logging:
      driver: none
